### PR TITLE
Adds Directory/File structure

### PR DESCRIPTION
**Pull request by dylanrh**
## Types of changes

- [ ] Bugfix (change which fixes an issue)
- [x] New feature (change which adds functionality)
- [ ] Refactor (change which changes the codebase without affecting its external behavior)
- [x] Non-breaking change (fix or feature that would causes existing functionality to work as expected)
- [ ] Breaking change (fix or feature that would cause existing functionality to __not__ work as expected)
## Purpose

Creating file structures now to avoid merge conflicts going forward 
## Approach

Initializing intuitive and methodical directory/file structure

### CODE REVIEW

**Review by VNguyenCode — APPROVED** [review]
This looks great, thanks for setting up.

**Review by guizzettic — APPROVED** [review]
Looks great, very professional file structure!

**Review by casesimmons — APPROVED** [review]
Reviewed & Approved

**Review by joonk025 — APPROVED** [review]
Approved!

**Pull request merged**
